// src/app/app.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  


}

<!-- <div style="display: flex; flex-direction: column; justify-content: space-between;">
<app-navbar></app-navbar>
<router-outlet></router-outlet>
<app-footer></app-footer>
</div> -->

<div style="height: 100vh; display: flex; flex-direction: column; justify-content: space-between;">
    <nav>
        <app-navbar></app-navbar>
    </nav>
    <router-outlet></router-outlet>
    <footer style="margin-top: auto">
        <app-footer></app-footer>
    </footer>
    </div>

// src/App.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router'
import HeaderNav from './components/nav/HeaderNav.vue';
import Footer from './components/nav/Footer.vue';
</script>

<template>
<div class="app-container bg-primary">
      <HeaderNav />

  <RouterView />

  <Footer />
</div>
</template>

<style scoped>

.app-container {
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}


</style>
